### ISSUE TITLE
Mobile signin for google not working

### ISSUE THREAD

**Issue by joebeernink** [TrashMob-eco/TrashMob#1019]
Google doesn't trust the browser (the blazor browser)

Have question out to MAUI/Blazor teams

**Comment by davidebbo** [comment]
For the record, this is the error I get:

Access blocked: Authorization Error

You can't sign in from this screen because this app doesn't comply with Google's secure browsers Policy. If this app has a website, you can open a web browser and try signing in from there.

Error 403: disallowed_useragent
